// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"GabeMeister/yer-cli/analyzer"
	helpers "GabeMeister/yer-cli/presentation/helpers"
	components "GabeMeister/yer-cli/presentation/views/components"
	"GabeMeister/yer-cli/utils"
	"fmt"
)

// The racing bar chart js requires that every author has an entry for every
// day, even if they didn't have any commits for that day
func expandData(recap analyzer.Recap) []analyzer.FileChangeDay {
	totalFileChangesPrevYear := recap.AuthorTotalFileChangesPrevYear
	fileChanges := recap.AuthorFileChangesOverTimeCurrYear
	allAuthors := recap.AllAuthors
	// e.g. [ '2025-01-01', '2025-01-02', ... ]
	dates := utils.GetDaysOfYear(analyzer.CURR_YEAR)

	// A map that just "keeps track" of the number of file changes each author has
	// as we iterate over each day. Used in case an author doesn't do any file
	// changes on a particular day
	fileChangeTracker := totalFileChangesPrevYear
	expandedFileChanges := []analyzer.FileChangeDay{}

	// For every date AND for every author, there needs to be an entry. Even if an
	// author doesn't commit anything for a particular day
	for _, date := range dates {
		for _, author := range allAuthors {
			var fileChangeAmt int

			key := fmt.Sprintf("%s|%s", date, author)
			val, found := fileChanges[key]

			if found {
				fileChangeAmt = val
			} else {
				// Use the previous day's file changes if no file changes were found for
				// this date
				fileChangeAmt = fileChangeTracker[author]
			}

			// Store it off so we remember for future days
			fileChangeTracker[key] = fileChangeAmt

			expandedFileChanges = append(expandedFileChanges, analyzer.FileChangeDay{
				Name:  author,
				Value: fileChangeAmt,
				Date:  date,
			})
		}
	}

	return expandedFileChanges
}

func AuthorFileChangesOverTimeCurrYear(recap analyzer.Recap) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"racing-bar-chart-container\" data-value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(helpers.Json(expandData(recap)))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `presentation/views/pages/EngineerFileChangesOverTimeCurrYear.templ`, Line: 59, Col: 83}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"p-12\"></div><div class=\"mt-12\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.NextButton(helpers.GetNextButtonLink("/author-file-changes-over-time-curr-year", recap)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = components.Slide().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
