#!/bin/bash

templ generate
npx tailwindcss --input ./presentation/styles/globals.css --output ./presentation/static/css/styles.css

echo "Building for Linux..."
GOOS=linux GOARCH=amd64 go build -o ~/dev/yer-cli/builds/yer_linux_amd64
GOOS=linux GOARCH=arm64 go build -o ~/dev/yer-cli/builds/yer_linux_arm64
echo "Building for Mac..."
GOOS=darwin GOARCH=amd64 go build -o ~/dev/yer-cli/builds/yer_darwin_amd64
GOOS=darwin GOARCH=arm64 go build -o ~/dev/yer-cli/builds/yer_darwin_arm64
echo "Building for Windows..."
GOOS=windows GOARCH=amd64 go build -o ~/dev/yer-cli/builds/yer_windows_amd64.exe
echo Done!