#!/bin/bash 

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "Linux operating system detected"
  curl -fsSL https://fly.storage.tigris.dev/year-end-recap-storage/yer_linux_amd64 --output year-end-recap
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac operating system detected"
  CPU_ARCH=$(uname -m)

  if [[ "$CPU_ARCH" == "arm64" ]]; then
    curl -fsSL https://fly.storage.tigris.dev/year-end-recap-storage/yer_darwin_arm64 --output year-end-recap
  elif [[ "$CPU_ARCH" == "x86_64" ]]; then
    curl -fsSL https://fly.storage.tigris.dev/year-end-recap-storage/yer_darwin_amd64 --output year-end-recap
  else
    echo "Unsupported Mac CPU architecture: $CPU_ARCH"
    exit 1
  fi
else
  echo "Unsupported Operating System: $OSTYPE"
  exit 1
fi

chmod +x year-end-recap
echo
echo Success! Year End Recap has been installed successfully.
echo

yellow='\033[1;33m'
reset='\033[0m'

echo -e "${yellow}┌──────────────────────────────────────┐${reset}"
echo -e "${yellow}│ To start, run the following command: │${reset}"
echo -e "${yellow}│                                      │${reset}"
echo -e "${yellow}│ ./year-end-recap -s                  │${reset}"
echo -e "${yellow}└──────────────────────────────────────┘${reset}"
echo 